This notebook covers the following:
* getLoad
    * examples (getChargingSessionData, getStation)
    * how to set input para
    * how to get info about input
* shedLoad

In [1]:
import zeep
from zeep import Settings
from zeep.wsse.username import UsernameToken

from zeep.helpers import serialize_object

import pandas as pd

from datetime import datetime, UTC

In [2]:
username = "4dca5ccc23852e8dff1d82b991884e4665bd76e6499461706915558"
password = "4dd12651108d532b7d35d0fe033af1a3"

# new credentials
username = '9c2fc57f048fd5c2f740dcf8e0a6f69c677c424289bda1736196674'
password = 'd67f1b3e02ff57fb6d90fc8a770db00b'

SERVICE_WSDL_URL = "https://webservices.fd.chargepoint.com/cp_api_5.1.wsdl"
# settins = Settings(strict=False, xml_huge_tree=True, xsd_ignore_sequence_order=True)
settins = Settings()

client = zeep.Client(
            SERVICE_WSDL_URL,
            wsse=UsernameToken(username, password),
            settings=settins,
        )

In [3]:
# similarly, for getLoad
def getLoad(query_para_dict={}):
    data_section_name = "stationData"
    searchQuery= client.get_type('ns0:sessionSearchdata')() 
    for k, v in query_para_dict.items():
        setattr(searchQuery, k, v)
    response_station = client.service.getLoad(searchQuery)
    # return response_station[data_section_name] #construct_data_session(responses, data_section_name)
    return response_station


# load_data = getLoad({"sessionID": 97885729})
# load_data = getLoad({"stationID": "1:13059121"})
load_data = getLoad({"stationID": "5:15504761"})
# load_data = getLoad({})
load_data

{
    'responseCode': '100',
    'responseText': 'API input request executed successfully.',
    'sgID': None,
    'numStations': 0,
    'groupName': None,
    'sgLoad': None,
    'stationData': [
        {
            'stationID': '5:15504761',
            'stationName': 'PNNL / MSL5',
            'Address': '1529 W Sequim Bay Rd, Sequim, Washington,  98382, United States',
            'stationLoad': Decimal('0.000'),
            'Port': [
                {
                    'portNumber': '1',
                    'userID': None,
                    'credentialID': 'CPFL0000205756',
                    'shedState': 0,
                    'portLoad': Decimal('0.000'),
                    'allowedLoad': Decimal('0.000'),
                    'percentShed': 0,
                    'sessionID': 103148769,
                    'lastBatteryPercent': 0.0
                },
                {
                    'portNumber': '2',
                    'userID': None,
                    'credentialID': None,
                    'shedState': 0,
                    'portLoad': Decimal('0.000'),
                    'allowedLoad': Decimal('0.000'),
                    'percentShed': 0,
                    'sessionID': 0,
                    'lastBatteryPercent': 0.0
                }
            ]
        }
    ]
}

In [4]:
# for better usability

def getLoadAPI(sgID=None, stationID=None, sessionID=None):
    # Note: 'Search by either sgID, sessionID or stationID', one and only one of them should be provided.
    searchQuery = {} 
    if sgID is not None:
        searchQuery.update({'sgID': sgID}) 
    if stationID is not None:
        searchQuery.update({'stationID': stationID}) 
    if sessionID is not None:
        searchQuery.update({'sessionID': sessionID}) 

    response = client.service.getLoad(searchQuery)
    
    if response["responseCode"] != "100":
                    # raise Exception(f"API error with response: {response}")
                    print(f"API error with response: {response}.")
                    return None
                
    return response

# Usage examples:
load_data_by_station = getLoadAPI(stationID="5:15504761")
load_data_by_session = getLoadAPI(sessionID=97885729)  # 101268659
load_data_by_sgID = getLoadAPI(sgID=12345)
load_data_by_non = getLoadAPI()

print(load_data_by_station)
print(load_data_by_session)
print(load_data_by_sgID)
print(load_data_by_non)

API error with response: {
    'responseCode': '160',
    'responseText': 'No data found for given criteria.',
    'sgID': None,
    'numStations': None,
    'groupName': None,
    'sgLoad': None,
    'stationData': []
}.
API error with response: {
    'responseCode': '160',
    'responseText': 'No data found for given criteria.',
    'sgID': None,
    'numStations': None,
    'groupName': None,
    'sgLoad': None,
    'stationData': []
}.
API error with response: {
    'responseCode': '182',
    'responseText': 'Search by either sgID, sessionID or stationID',
    'sgID': None,
    'numStations': None,
    'groupName': None,
    'sgLoad': None,
    'stationData': []
}.
{
    'responseCode': '100',
    'responseText': 'API input request executed successfully.',
    'sgID': None,
    'numStations': 0,
    'groupName': None,
    'sgLoad': None,
    'stationData': [
        {
            'stationID': '5:15504761',
            'stationName': 'PNNL / MSL5',
            'Address': '1529 W Sequim Bay Rd, Sequim, Washington,  98382, United States',
            'stationLoad': Decimal('0.000'),
            'Port': [
                {
                    'portNumber': '1',
                    'userID': None,
                    'credentialID': 'CPFL0000205756',
                    'shedState': 0,
                    'portLoad': Decimal('0.000'),
                    'allowedLoad': Decimal('0.000'),
                    'percentShed': 0,
                    'sessionID': 103148769,
                    'lastBatteryPercent': 0.0
                },
                {
                    'portNumber': '2',
                    'userID': None,
                    'credentialID': None,
                    'shedState': 0,
                    'portLoad': Decimal('0.000'),
                    'allowedLoad': Decimal('0.000'),
                    'percentShed': 0,
                    'sessionID': 0,
                    'lastBatteryPercent': 0.0
                }
            ]
        }
    ]
}
None
None
None

In [5]:
load_data_by_non

In [6]:
load_data_by_session

In [7]:
getLoadAPI(sessionID=101268659)  # 101268659

API error with response: {
    'responseCode': '160',
    'responseText': 'No data found for given criteria.',
    'sgID': None,
    'numStations': None,
    'groupName': None,
    'sgLoad': None,
    'stationData': []
}.

In [8]:
getLoadAPI(sessionID=103148769)

{
    'responseCode': '100',
    'responseText': 'API input request executed successfully.',
    'sgID': None,
    'numStations': 0,
    'groupName': None,
    'sgLoad': None,
    'stationData': [
        {
            'stationID': '5:15504761',
            'stationName': 'PNNL / MSL5',
            'Address': '1529 W Sequim Bay Rd, Sequim, Washington,  98382, United States',
            'stationLoad': Decimal('0.000'),
            'Port': [
                {
                    'portNumber': '1',
                    'userID': None,
                    'credentialID': 'CPFL0000205756',
                    'shedState': 0,
                    'portLoad': Decimal('0.000'),
                    'allowedLoad': Decimal('0.000'),
                    'percentShed': 0,
                    'sessionID': 103148769,
                    'lastBatteryPercent': 0.0
                }
            ]
        }
    ]
}

In [9]:
load_data_by_station

{
    'responseCode': '100',
    'responseText': 'API input request executed successfully.',
    'sgID': None,
    'numStations': 0,
    'groupName': None,
    'sgLoad': None,
    'stationData': [
        {
            'stationID': '5:15504761',
            'stationName': 'PNNL / MSL5',
            'Address': '1529 W Sequim Bay Rd, Sequim, Washington,  98382, United States',
            'stationLoad': Decimal('0.000'),
            'Port': [
                {
                    'portNumber': '1',
                    'userID': None,
                    'credentialID': 'CPFL0000205756',
                    'shedState': 0,
                    'portLoad': Decimal('0.000'),
                    'allowedLoad': Decimal('0.000'),
                    'percentShed': 0,
                    'sessionID': 103148769,
                    'lastBatteryPercent': 0.0
                },
                {
                    'portNumber': '2',
                    'userID': None,
                    'credentialID': None,
                    'shedState': 0,
                    'portLoad': Decimal('0.000'),
                    'allowedLoad': Decimal('0.000'),
                    'percentShed': 0,
                    'sessionID': 0,
                    'lastBatteryPercent': 0.0
                }
            ]
        }
    ]
}

In [10]:
serialized_res = serialize_object(load_data_by_station)
serialized_res

OrderedDict([('responseCode', '100'),
             ('responseText', 'API input request executed successfully.'),
             ('sgID', None),
             ('numStations', 0),
             ('groupName', None),
             ('sgLoad', None),
             ('stationData',
              [OrderedDict([('stationID', '5:15504761'),
                            ('stationName', 'PNNL / MSL5'),
                            ('Address',
                             '1529 W Sequim Bay Rd, Sequim, Washington,  98382, United States'),
                            ('stationLoad', Decimal('0.000')),
                            ('Port',
                             [OrderedDict([('portNumber', '1'),
                                           ('userID', None),
                                           ('credentialID', 'CPFL0000205756'),
                                           ('shedState', 0),
                                           ('portLoad', Decimal('0.000')),
                                           ('allowedLoad', Decimal('0.000')),
                                           ('percentShed', 0),
                                           ('sessionID', 103148769),
                                           ('lastBatteryPercent', 0.0)]),
                              OrderedDict([('portNumber', '2'),
                                           ('userID', None),
                                           ('credentialID', None),
                                           ('shedState', 0),
                                           ('portLoad', Decimal('0.000')),
                                           ('allowedLoad', Decimal('0.000')),
                                           ('percentShed', 0),
                                           ('sessionID', 0),
                                           ('lastBatteryPercent',
                                            0.0)])])])])])

In [11]:
df = pd.json_normalize(
    serialized_res['stationData'], 
    record_path='Port', 
    meta=[
        'stationID', 
        'stationName', 
        'Address', 
        'stationLoad'
    ]
)
# filter out the sessionID = 0 (invalid sessionID)
df = df[df["sessionID"] != 0]

# add "queryTime" column
df["queryTimeUTC"] = pd.to_datetime(datetime.now(UTC))

df

# df.to_dict(orient='records')

,portNumber,userID,credentialID,shedState,portLoad,allowedLoad,percentShed,sessionID,lastBatteryPercent,stationID,stationName,Address,stationLoad,queryTimeUTC
0,1,None,CPFL0000205756,0,0.000,0.000,0,103148769,0.0,5:15504761,PNNL / MSL5,"1529 W Sequim Bay Rd, Sequim, Washington, 983...",0.000,2025-02-20 05:53:40.761480+00:00

In [12]:
pd.json_normalize(serialized_res["stationData"])

,stationID,stationName,Address,stationLoad,Port
0,5:15504761,PNNL / MSL5,"1529 W Sequim Bay Rd, Sequim, Washington, 983...",0.000,"[{'portNumber': '1', 'userID': None, 'credenti..."

Note: If you use the shedLoad call with the percentShedPerStation or percentShedPerPort parameter on a station that is not delivering any power, the maximum output is set to 0 kW, and charging will not be allowed on that station until the shed period ends or a call to clearShedState is made.

In [13]:
# similarly, for shedLoad
def shedLoad(query_para_dict={}):
    data_section_name = "stationData"
    searchQuery= client.get_type('ns0:sessionSearchdata')() 
    for k, v in query_para_dict.items():
        setattr(searchQuery, k, v)
    response_station = client.service.shedLoad(searchQuery)
    # return response_station[data_section_name] #construct_data_session(responses, data_section_name)
    return response_station


# load_data = getLoad({"sessionID": 97885729})
# load_data = getLoad({"stationID": "1:13059121"})
shed_load_response = shedLoad({"stationID": "5:15504761", "timeInterval": 1, "allowedLoadPerPort": 0, "portNumber": 1})
# load_data = getLoad({})
print(f"{shed_load_response = }")

print(f'{getLoad({"stationID": "5:15504761"}) = }')

shed_load_response = {
    'responseCode': '172',
    'responseText': 'Please provide all the mandatory fields to make this call.',
    'Success': None,
    'sgID': None,
    'stationID': None,
    'allowedLoadPerStation': None,
    'percentShedPerStation': None,
    'Ports': None
}
getLoad({"stationID": "5:15504761"}) = {
    'responseCode': '100',
    'responseText': 'API input request executed successfully.',
    'sgID': None,
    'numStations': 0,
    'groupName': None,
    'sgLoad': None,
    'stationData': [
        {
            'stationID': '5:15504761',
            'stationName': 'PNNL / MSL5',
            'Address': '1529 W Sequim Bay Rd, Sequim, Washington,  98382, United States',
            'stationLoad': Decimal('0.000'),
            'Port': [
                {
                    'portNumber': '1',
                    'userID': None,
                    'credentialID': 'CPFL0000205756',
                    'shedState': 0,
                    'portLoad': Decimal('0.000'),
                    'allowedLoad': Decimal('0.000'),
                    'percentShed': 0,
                    'sessionID': 103148769,
                    'lastBatteryPercent': 0.0
                },
                {
                    'portNumber': '2',
                    'userID': None,
                    'credentialID': None,
                    'shedState': 0,
                    'portLoad': Decimal('0.000'),
                    'allowedLoad': Decimal('0.000'),
                    'percentShed': 0,
                    'sessionID': 0,
                    'lastBatteryPercent': 0.0
                }
            ]
        }
    ]
}

In [14]:
# similarly, for shedLoad
def clearShedState(query_para_dict={}):
    data_section_name = "stationData"
    searchQuery= client.get_type('ns0:sessionSearchdata')() 
    for k, v in query_para_dict.items():
        setattr(searchQuery, k, v)
    print(f"{searchQuery = }")
    response_station = client.service.clearShedState(query_para_dict)
    # return response_station[data_section_name] #construct_data_session(responses, data_section_name)
    return response_station


# load_data = getLoad({"sessionID": 97885729})
# load_data = getLoad({"stationID": "1:13059121"})
clear_shed_response = clearShedState({"stationID": "5:15504761", })  
# load_data = getLoad({})
print(f"{clear_shed_response = }")

print(f'{getLoad({"stationID": "5:15504761"}) = }')

searchQuery = {
    'stationID': '5:15504761',
    'sessionID': None,
    'userID': None,
    'stationName': None,
    'Address': None,
    'City': None,
    'State': None,
    'Country': None,
    'postalCode': None,
    'Proximity': None,
    'proximityUnit': None,
    'fromTimeStamp': None,
    'toTimeStamp': None,
    'startRecord': None,
    'Geo': None,
    'stationIDs': None,
    'activeSessionsOnly': None
}
clear_shed_response = {
    'responseCode': '184',
    'responseText': 'Enter either sgid or stationID',
    'Success': None,
    'sgID': None,
    'stationID': None
}
getLoad({"stationID": "5:15504761"}) = {
    'responseCode': '100',
    'responseText': 'API input request executed successfully.',
    'sgID': None,
    'numStations': 0,
    'groupName': None,
    'sgLoad': None,
    'stationData': [
        {
            'stationID': '5:15504761',
            'stationName': 'PNNL / MSL5',
            'Address': '1529 W Sequim Bay Rd, Sequim, Washington,  98382, United States',
            'stationLoad': Decimal('0.000'),
            'Port': [
                {
                    'portNumber': '1',
                    'userID': None,
                    'credentialID': 'CPFL0000205756',
                    'shedState': 0,
                    'portLoad': Decimal('0.000'),
                    'allowedLoad': Decimal('0.000'),
                    'percentShed': 0,
                    'sessionID': 103148769,
                    'lastBatteryPercent': 0.0
                },
                {
                    'portNumber': '2',
                    'userID': None,
                    'credentialID': None,
                    'shedState': 0,
                    'portLoad': Decimal('0.000'),
                    'allowedLoad': Decimal('0.000'),
                    'percentShed': 0,
                    'sessionID': 0,
                    'lastBatteryPercent': 0.0
                }
            ]
        }
    ]
}

In [15]:
# verify session id 102543439
kwargs = {}
# kwargs = {"City": "Sequim", 'stationName':'PNNL / MSL5'}
# station_id = "1:15504761"
# searchQuery = client.get_type("ns0:sessionSearchdata")()
# for k, v in kwargs.items():
#     setattr(searchQuery, k, v)
session_data = client.service.getChargingSessionData({'sessionID': 102543439})
print(session_data)

session_data = client.service.getChargingSessionData({'sessionID': 79776929})
print(session_data)

{
    'responseCode': '100',
    'responseText': 'API input request executed successfully.',
    'ChargingSessionData': [
        {
            'stationID': '5:15504761',
            'stationName': 'PNNL / MSL5',
            'portNumber': '1',
            'Address': '1529 W Sequim Bay Rd, Sequim, Washington, 98382, United States',
            'City': 'Sequim',
            'State': 'Washington',
            'Country': 'United States',
            'postalCode': '98382',
            'sessionID': 102543439,
            'Energy': 3.840849,
            'startTime': datetime.datetime(2025, 2, 14, 18, 3, 39, tzinfo=<isodate.tzinfo.Utc object at 0x7fe494b93e60>),
            'endTime': datetime.datetime(2025, 2, 14, 21, 37, 15, tzinfo=<isodate.tzinfo.Utc object at 0x7fe494b93e60>),
            'totalChargingDuration': '00:42:10',
            'totalSessionDuration': '03:33:36',
            'userID': None,
            'startBatteryPercentage': 0.0,
            'stopBatteryPercentage': 0.0,
            'recordNumber': 1,
            'credentialID': 'CPFL0000205756',
            'endedBy': 'Plug Out at Vehicle',
            'vehicleMake': None,
            'vehicleModel': None,
            'vehicleModelYear': None,
            'vehicleType': None,
            'vehiclePortMAC': None,
            'driverOptedOut': None,
            'driverOptOutTimestamp': None,
            'paymentTerminalInfo': None
        }
    ],
    'MoreFlag': 0
}
{
    'responseCode': '100',
    'responseText': 'API input request executed successfully.',
    'ChargingSessionData': [
        {
            'stationID': '5:13090571',
            'stationName': 'PNNL / EMSL 9',
            'portNumber': '1',
            'Address': '650 Horn Rapids Rd, Richland, Washington, 99354, United States',
            'City': 'Richland',
            'State': 'Washington',
            'Country': 'United States',
            'postalCode': '99354',
            'sessionID': 79776929,
            'Energy': 0.0,
            'startTime': datetime.datetime(2024, 5, 4, 17, 27, 31, tzinfo=<isodate.tzinfo.Utc object at 0x7fe494b93e60>),
            'endTime': datetime.datetime(2024, 5, 4, 17, 29, 32, tzinfo=<isodate.tzinfo.Utc object at 0x7fe494b93e60>),
            'totalChargingDuration': '00:00:00',
            'totalSessionDuration': '00:02:01',
            'userID': '49852681',
            'startBatteryPercentage': 0.0,
            'stopBatteryPercentage': 0.0,
            'recordNumber': 1,
            'credentialID': 'YzM1NTJiZTEtODU5My00',
            'endedBy': 'Timeout',
            'vehicleMake': None,
            'vehicleModel': None,
            'vehicleModelYear': None,
            'vehicleType': None,
            'vehiclePortMAC': None,
            'driverOptedOut': None,
            'driverOptOutTimestamp': None,
            'paymentTerminalInfo': None
        }
    ],
    'MoreFlag': 0
}